<?php
/**
 * Public login URL router.
 *
 * This module makes /login the branded public entry point while leaving the
 * native WordPress login controller in charge of authentication, password
 * resets, logout, remember-me, nonces, and redirect handling.
 *
 * @package GatiCrew_Events_Bridge
 */

defined( 'ABSPATH' ) || exit;

final class GatiCrew_Events_Bridge_Login_Router {
	const LOGIN_SLUG      = 'login';
	const REWRITE_VERSION = 'gaticrew-login-v4';

	/**
	 * Registers routing, URL filters, and legacy-login redirects.
	 *
	 * @return void
	 */
	public function init() {
		add_action( 'init', array( __CLASS__, 'register_rewrite_rules' ), 1 );
		add_action( 'init', array( $this, 'maybe_flush_rewrite_rules' ), 30 );
		add_action( 'login_init', array( $this, 'redirect_legacy_login_request' ), 0 );

		add_filter( 'login_url', array( $this, 'filter_login_url' ), 10, 3 );
		add_filter( 'lostpassword_url', array( $this, 'filter_lostpassword_url' ), 10, 2 );
		add_filter( 'register_url', array( $this, 'filter_register_url' ) );
		add_filter( 'site_url', array( $this, 'filter_wp_login_url' ), 10, 4 );
		add_filter( 'network_site_url', array( $this, 'filter_wp_login_url' ), 10, 3 );
	}

	/**
	 * Adds an Apache-level rewrite from /login to wp-login.php.
	 *
	 * The target intentionally remains wp-login.php so WordPress core continues
	 * to own all authentication actions. Query strings are preserved by the
	 * rewrite engine, so /login?action=lostpassword works normally.
	 *
	 * @return void
	 */
	public static function register_rewrite_rules() {
		add_filter( 'mod_rewrite_rules', array( __CLASS__, 'inject_login_rewrite_rule' ) );
	}

	/**
	 * Adds the /login rewrite before WordPress' catch-all index.php rule.
	 *
	 * add_rewrite_rule() alone is not enough for this route because wp-login.php
	 * is a front-controller PHP file, not a normal WordPress template. This
	 * filter keeps the rule inside WordPress-managed .htaccess output.
	 *
	 * @param string $rules Generated Apache rewrite rules.
	 * @return string
	 */
	public static function inject_login_rewrite_rule( $rules ) {
		if ( false !== strpos( $rules, '# BEGIN GatiCrew Login Router' ) ) {
			return $rules;
		}

		$login_rule = "\n# BEGIN GatiCrew Login Router\nRewriteRule ^" . self::LOGIN_SLUG . "/?$ wp-login.php [QSA,L]\n# END GatiCrew Login Router\n";

		if ( false !== strpos( $rules, "RewriteBase " ) ) {
			return preg_replace( '/(RewriteBase[^\r\n]*(?:\r\n|\n|\r))/', '$1' . $login_rule, $rules, 1 );
		}

		return $login_rule . $rules;
	}

	/**
	 * Flushes rewrites once after this router is deployed or versioned.
	 *
	 * @return void
	 */
	public function maybe_flush_rewrite_rules() {
		if ( self::REWRITE_VERSION === get_option( 'gaticrew_events_bridge_login_rewrite_version' ) ) {
			return;
		}

		self::register_rewrite_rules();
		flush_rewrite_rules( true );
		update_option( 'gaticrew_events_bridge_login_rewrite_version', self::REWRITE_VERSION, false );
	}

	/**
	 * Rewrites WordPress-generated login URLs to /login.
	 *
	 * @param string $login_url Login URL generated by WordPress.
	 * @param string $redirect Optional redirect target.
	 * @param bool   $force_reauth Whether reauth is required.
	 * @return string
	 */
	public function filter_login_url( $login_url, $redirect, $force_reauth ) {
		unset( $login_url );

		$args = array();

		if ( ! empty( $redirect ) ) {
			$args['redirect_to'] = $redirect;
		}

		if ( $force_reauth ) {
			$args['reauth'] = '1';
		}

		return $this->build_login_url( $args );
	}

	/**
	 * Rewrites lost-password URLs to /login?action=lostpassword.
	 *
	 * @param string $lostpassword_url Generated URL.
	 * @param string $redirect Optional redirect target.
	 * @return string
	 */
	public function filter_lostpassword_url( $lostpassword_url, $redirect ) {
		unset( $lostpassword_url );

		$args = array(
			'action' => 'lostpassword',
		);

		if ( ! empty( $redirect ) ) {
			$args['redirect_to'] = $redirect;
		}

		return $this->build_login_url( $args );
	}

	/**
	 * Rewrites registration URLs when registration is enabled.
	 *
	 * @return string
	 */
	public function filter_register_url() {
		return $this->build_login_url(
			array(
				'action' => 'register',
			)
		);
	}

	/**
	 * Rewrites direct wp-login.php URLs generated by core/plugins.
	 *
	 * @param string $url Generated URL.
	 * @param string $path Requested path.
	 * @param string $scheme URL scheme.
	 * @param int    $blog_id Optional blog ID for site_url filter.
	 * @return string
	 */
	public function filter_wp_login_url( $url, $path, $scheme, $blog_id = null ) {
		unset( $scheme, $blog_id );

		$path = (string) $path;

		if ( ! $this->is_wp_login_path( $path ) ) {
			return $url;
		}

		$query = wp_parse_url( $path, PHP_URL_QUERY );
		$args  = array();

		if ( is_string( $query ) && '' !== $query ) {
			wp_parse_str( $query, $args );
		}

		return $this->build_login_url( $args );
	}

	/**
	 * Redirects public legacy wp-login.php GET requests to /login.
	 *
	 * POST requests are intentionally allowed so stale form submissions do not
	 * lose credentials. Fresh login forms generated by WordPress now post to
	 * /login through the URL filters above.
	 *
	 * @return void
	 */
	public function redirect_legacy_login_request() {
		if ( ! $this->is_legacy_login_request() || $this->is_pretty_login_request() ) {
			return;
		}

		$method = isset( $_SERVER['REQUEST_METHOD'] ) ? strtoupper( sanitize_text_field( wp_unslash( $_SERVER['REQUEST_METHOD'] ) ) ) : 'GET';

		if ( 'GET' !== $method && 'HEAD' !== $method ) {
			return;
		}

		wp_safe_redirect( $this->build_login_url( $this->get_current_query_args() ), 302 );
		exit;
	}

	/**
	 * Builds the public branded login URL.
	 *
	 * @param array $args Optional query args.
	 * @return string
	 */
	private function build_login_url( $args = array() ) {
		$url  = home_url( '/' . self::LOGIN_SLUG . '/' );
		$args = is_array( $args ) ? array_filter( $args, array( $this, 'is_non_empty_query_value' ) ) : array();

		return empty( $args ) ? $url : add_query_arg( $args, $url );
	}

	/**
	 * Returns safe query args from the current request.
	 *
	 * @return array
	 */
	private function get_current_query_args() {
		$request_uri = isset( $_SERVER['REQUEST_URI'] ) ? esc_url_raw( wp_unslash( $_SERVER['REQUEST_URI'] ) ) : '';
		$query       = wp_parse_url( $request_uri, PHP_URL_QUERY );
		$args        = array();

		if ( is_string( $query ) && '' !== $query ) {
			wp_parse_str( $query, $args );
		}

		return is_array( $args ) ? $args : array();
	}

	/**
	 * Checks if the current browser URL is /login.
	 *
	 * @return bool
	 */
	private function is_pretty_login_request() {
		return self::LOGIN_SLUG === $this->get_relative_request_path();
	}

	/**
	 * Checks if the current browser URL is wp-login.php.
	 *
	 * @return bool
	 */
	private function is_legacy_login_request() {
		return 'wp-login.php' === $this->get_relative_request_path();
	}

	/**
	 * Normalizes the request path relative to the WordPress home path.
	 *
	 * @return string
	 */
	private function get_relative_request_path() {
		$request_uri = isset( $_SERVER['REQUEST_URI'] ) ? esc_url_raw( wp_unslash( $_SERVER['REQUEST_URI'] ) ) : '';
		$path        = wp_parse_url( $request_uri, PHP_URL_PATH );

		if ( ! is_string( $path ) ) {
			return '';
		}

		$path           = '/' . ltrim( $path, '/' );
		$home_path      = wp_parse_url( home_url( '/' ), PHP_URL_PATH );
		$home_path      = is_string( $home_path ) ? trim( $home_path, '/' ) : '';
		$home_path      = '' === $home_path ? '/' : '/' . $home_path . '/';

		if ( '/' !== $home_path && 0 === strpos( trailingslashit( $path ), $home_path ) ) {
			$path = substr( $path, strlen( untrailingslashit( $home_path ) ) );
		}

		return trim( $path, '/' );
	}

	/**
	 * Checks generated URL paths for wp-login.php.
	 *
	 * @param string $path URL path.
	 * @return bool
	 */
	private function is_wp_login_path( $path ) {
		$path_only = wp_parse_url( $path, PHP_URL_PATH );

		if ( ! is_string( $path_only ) ) {
			$path_only = $path;
		}

		return 'wp-login.php' === basename( trim( $path_only, '/' ) );
	}

	/**
	 * Keeps valid "0" query values while removing null/empty-string values.
	 *
	 * @param mixed $value Query value.
	 * @return bool
	 */
	private function is_non_empty_query_value( $value ) {
		return null !== $value && '' !== $value;
	}
}
