<?php
/**
 * QR ticket validation and check-in route.
 *
 * @package GatiCrew_Events_Bridge
 */

defined( 'ABSPATH' ) || exit;

final class GatiCrew_Events_Bridge_Checkin_Controller {
	/**
	 * Public query var for scanned booking IDs.
	 */
	const QUERY_VAR_TOKEN = 'gaticrew_checkin_token';

	/**
	 * Attendee repository.
	 *
	 * @var GatiCrew_Events_Bridge_Attendees_Repository
	 */
	private $attendees_repository;

	/**
	 * Constructor.
	 */
	public function __construct() {
		$this->attendees_repository = new GatiCrew_Events_Bridge_Attendees_Repository();
	}

	/**
	 * Registers rewrite and validation hooks.
	 *
	 * @return void
	 */
	public function init() {
		add_action( 'init', array( __CLASS__, 'register_rewrite_rules' ) );
		add_action( 'init', array( $this, 'maybe_flush_rewrite_rules' ), 20 );
		add_filter( 'query_vars', array( $this, 'register_query_vars' ) );
		add_action( 'template_redirect', array( $this, 'handle_checkin_request' ) );
		add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_assets' ) );
	}

	/**
	 * Registers /checkin/{booking_id} route and keeps the original route as a
	 * compatibility alias for QR codes generated by earlier builds.
	 *
	 * @return void
	 */
	public static function register_rewrite_rules() {
		add_rewrite_rule(
			'^checkin/([A-Za-z0-9-]+)/?$',
			'index.php?' . self::QUERY_VAR_TOKEN . '=$matches[1]',
			'top'
		);
		add_rewrite_rule(
			'^gaticrew-checkin/([A-Za-z0-9-]+)/?$',
			'index.php?' . self::QUERY_VAR_TOKEN . '=$matches[1]',
			'top'
		);
	}

	/**
	 * Flushes rewrites once after plugin upgrades add the check-in route.
	 *
	 * @return void
	 */
	public function maybe_flush_rewrite_rules() {
		$rewrite_version = 'gaticrew-checkin-v2';

		if ( $rewrite_version === get_option( 'gaticrew_events_bridge_rewrite_version' ) ) {
			return;
		}

		flush_rewrite_rules( false );
		update_option( 'gaticrew_events_bridge_rewrite_version', $rewrite_version, false );
	}

	/**
	 * Adds the QR token query var.
	 *
	 * @param array $vars Public query vars.
	 * @return array
	 */
	public function register_query_vars( $vars ) {
		$vars[] = self::QUERY_VAR_TOKEN;

		return $vars;
	}

	/**
	 * Loads validation styling on scanned-ticket routes.
	 *
	 * @return void
	 */
	public function enqueue_assets() {
		if ( '' === $this->get_raw_request_token() ) {
			return;
		}

		wp_enqueue_style(
			'gaticrew-events-bridge-frontend',
			GATICREW_EVENTS_BRIDGE_URL . 'assets/css/frontend.css',
			array(),
			GATICREW_EVENTS_BRIDGE_VERSION
		);
	}

	/**
	 * Handles QR validation and check-in actions.
	 *
	 * @return void
	 */
	public function handle_checkin_request() {
		$raw_token = $this->get_raw_request_token();

		if ( '' === $raw_token ) {
			return;
		}

		nocache_headers();
		$token = GatiCrew_Events_Bridge_QR_Tokens::sanitize_token( $raw_token );

		if ( $this->is_rate_limited() ) {
			status_header( 429 );
			$this->render_checkin_page( null, 'rate_limited' );
			exit;
		}

		$attendee = '' !== $token ? $this->attendees_repository->get_by_qr_token( $token ) : null;
		$attendee_group = '' !== $token ? $this->attendees_repository->get_group_by_qr_token( $token ) : array();

		if ( empty( $attendee ) ) {
			$this->record_failed_attempt();
			status_header( 404 );
			$this->render_checkin_page( null, 'invalid_token' );
			exit;
		}

		$notice = '';

		if ( $this->is_mark_checkin_request() ) {
			$notice = $this->handle_mark_checked_in( $token );
			$attendee = $this->attendees_repository->get_by_qr_token( $token );
			$attendee_group = $this->attendees_repository->get_group_by_qr_token( $token );
		}

		status_header( 200 );
		$this->render_checkin_page( $attendee, $notice, $attendee_group );
		exit;
	}

	/**
	 * Returns sanitized booking ID/token from the current request.
	 *
	 * @return string
	 */
	private function get_request_token() {
		return GatiCrew_Events_Bridge_QR_Tokens::sanitize_token( get_query_var( self::QUERY_VAR_TOKEN ) );
	}

	/**
	 * Returns raw token query var when the check-in route matched.
	 *
	 * @return string
	 */
	private function get_raw_request_token() {
		return sanitize_text_field( (string) get_query_var( self::QUERY_VAR_TOKEN ) );
	}

	/**
	 * Determines whether the current request is a check-in POST.
	 *
	 * @return bool
	 */
	private function is_mark_checkin_request() {
		return isset( $_POST['gaticrew_checkin_action'] )
			&& 'mark_checked_in' === sanitize_key( wp_unslash( $_POST['gaticrew_checkin_action'] ) );
	}

	/**
	 * Securely marks a booking checked in for a valid token.
	 *
	 * @param string $token Booking ID or legacy QR token.
	 * @return string Notice key.
	 */
	private function handle_mark_checked_in( $token ) {
		$nonce = isset( $_POST['_wpnonce'] ) ? sanitize_text_field( wp_unslash( $_POST['_wpnonce'] ) ) : '';

		if ( ! wp_verify_nonce( $nonce, 'gaticrew_checkin_' . $token ) ) {
			return 'invalid_nonce';
		}

		$result = $this->attendees_repository->mark_checked_in_by_token( $token );

		return isset( $result['code'] ) ? sanitize_key( $result['code'] ) : 'checkin_failed';
	}

	/**
	 * Renders the standalone check-in validation experience.
	 *
	 * @param array|null $attendee Attendee row.
	 * @param string     $notice Notice key.
	 * @return void
	 */
	private function render_checkin_page( $attendee, $notice, $attendee_group = array() ) {
		$token = is_array( $attendee ) && ! empty( $attendee['qr_token'] )
			? GatiCrew_Events_Bridge_QR_Tokens::sanitize_token( $attendee['qr_token'] )
			: $this->get_request_token();

		include GATICREW_EVENTS_BRIDGE_PATH . 'templates/checkin-validation.php';
	}

	/**
	 * Protects the public validation route from repeated invalid-token probing.
	 *
	 * @return bool
	 */
	private function is_rate_limited() {
		$key = $this->get_rate_limit_key();

		if ( '' === $key ) {
			return false;
		}

		return absint( get_transient( $key ) ) >= 20;
	}

	/**
	 * Records a failed validation attempt for the requester.
	 *
	 * @return void
	 */
	private function record_failed_attempt() {
		$key = $this->get_rate_limit_key();

		if ( '' === $key ) {
			return;
		}

		$count = absint( get_transient( $key ) );
		set_transient( $key, $count + 1, 15 * MINUTE_IN_SECONDS );
	}

	/**
	 * Builds a privacy-preserving rate-limit key from the requester IP.
	 *
	 * @return string
	 */
	private function get_rate_limit_key() {
		$ip = isset( $_SERVER['REMOTE_ADDR'] ) ? sanitize_text_field( wp_unslash( $_SERVER['REMOTE_ADDR'] ) ) : '';

		if ( '' === $ip ) {
			return '';
		}

		return 'gaticrew_checkin_fail_' . hash( 'sha256', $ip . wp_salt( 'nonce' ) );
	}
}
