<?php
/**
 * Event Tickets attendee synchronization.
 *
 * The frontend booking API creates WooCommerce orders directly, which bypasses
 * Event Tickets' normal checkout pipeline. This bridge uses Event Tickets'
 * official Tickets Commerce APIs to create real TEC attendee posts so QR
 * security codes, QR images, and TEC scanner validation remain authoritative.
 *
 * @package GatiCrew_Events_Bridge
 */

defined( 'ABSPATH' ) || exit;

final class GatiCrew_Events_Bridge_Event_Tickets_Sync {
	/**
	 * Bridge-owned attendee meta linking real Event Tickets attendees to Woo.
	 */
	const META_BOOKING_ID        = '_gaticrew_booking_id';
	const META_WOO_ORDER_ID      = '_gaticrew_woo_order_id';
	const META_WOO_ORDER_ITEM_ID = '_gaticrew_woo_order_item_id';
	const META_TICKET_INDEX      = '_gaticrew_ticket_index';
	const META_SOURCE_PRODUCT_ID = '_gaticrew_source_product_id';
	const META_CUSTOMER_PHONE    = '_gaticrew_customer_phone';

	/**
	 * Bridge-owned ticket meta for auto-created Tickets Commerce tickets.
	 */
	const META_BRIDGE_TICKET     = '_gaticrew_bridge_ticket';
	const META_BRIDGE_PRODUCT_ID = '_gaticrew_bridge_product_id';

	/**
	 * Ensures a WooCommerce booking order has real Event Tickets attendees.
	 *
	 * @param WC_Order $order WooCommerce order generated by the bridge.
	 * @return array Event Tickets attendee post IDs.
	 */
	public static function sync_order( WC_Order $order ) {
		if ( ! self::is_tickets_commerce_available() ) {
			self::debug_log( 'Event Tickets Commerce is unavailable; real attendee generation skipped.' );
			return array();
		}

		$order_id   = absint( $order->get_id() );
		$booking_id = self::get_order_booking_id( $order );
		$event_id   = self::get_order_event_id( $order );
		$product_id = self::get_order_product_id( $order, $event_id );

		if ( ! $order_id || '' === $booking_id || ! $event_id ) {
			self::debug_log( 'Missing order, booking, or event data for Event Tickets sync. Order ID: ' . $order_id );
			return array();
		}

		$quantity = self::get_order_quantity( $order, $event_id );

		if ( 0 >= $quantity ) {
			self::debug_log( 'No ticket quantity found for Event Tickets sync. Order ID: ' . $order_id );
			return array();
		}

		$existing = self::get_existing_attendee_ids( $order_id, $booking_id, $event_id );

		if ( count( $existing ) >= $quantity ) {
			self::sync_existing_attendee_rows( array_slice( $existing, 0, $quantity ), $order, $booking_id, $event_id );
			self::debug_log( 'Event Tickets attendees already exist for order ' . $order_id . ', booking ' . $booking_id );
			return array_slice( $existing, 0, $quantity );
		}

		$ticket_id = self::get_or_create_ticket( $event_id, $product_id );

		if ( ! $ticket_id ) {
			throw new RuntimeException( __( 'Event Tickets ticket could not be resolved for this event.', 'gaticrew-events-bridge' ) );
		}

		$customer       = self::get_customer_data( $order );
		$attendee_names = self::get_order_attendee_names( $order, $quantity, $customer['name'] );
		$created        = $existing;

		for ( $index = 1; $index <= $quantity; $index++ ) {
			$existing_id = self::get_existing_attendee_id_for_index( $order_id, $booking_id, $index );

			if ( $existing_id ) {
				self::persist_tec_attendee_to_row( $existing_id, $order, $booking_id, $index, $event_id );
				$created[] = $existing_id;
				continue;
			}

			$name     = ! empty( $attendee_names[ $index - 1 ] ) ? $attendee_names[ $index - 1 ] : $customer['name'];
			$attendee = self::create_event_tickets_attendee( $ticket_id, $name, $customer['email'] );

			if ( is_wp_error( $attendee ) ) {
				self::debug_log( 'Event Tickets attendee creation failed: ' . $attendee->get_error_message() );
				throw new RuntimeException( $attendee->get_error_message() );
			}

			if ( ! $attendee instanceof WP_Post ) {
				self::debug_log( 'Event Tickets attendee creation returned an invalid response for order ' . $order_id );
				throw new RuntimeException( __( 'Event Tickets attendee could not be created.', 'gaticrew-events-bridge' ) );
			}

			self::tag_attendee( $attendee->ID, $order, $booking_id, $event_id, $product_id, $index, $name, $customer );
			self::persist_tec_attendee_to_row( $attendee->ID, $order, $booking_id, $index, $event_id );
			$created[] = absint( $attendee->ID );
		}

		$created = array_values( array_unique( array_map( 'absint', $created ) ) );
		self::debug_log( 'Event Tickets sync complete for order ' . $order_id . '. Attendees: ' . implode( ',', $created ) );

		return $created;
	}

	/**
	 * Checks that the free Event Tickets Tickets Commerce provider is loaded.
	 *
	 * @return bool
	 */
	private static function is_tickets_commerce_available() {
		return function_exists( 'tribe' )
			&& function_exists( 'tec_tc_tickets' )
			&& function_exists( 'tec_tc_attendees' )
			&& class_exists( 'TEC\Tickets\Commerce\Module' )
			&& class_exists( 'TEC\Tickets\Commerce\Ticket' );
	}

	/**
	 * Gets an existing TEC ticket for the event or creates one with TEC APIs.
	 *
	 * @param int $event_id Event post ID.
	 * @param int $product_id Linked WooCommerce product ID.
	 * @return int
	 */
	private static function get_or_create_ticket( $event_id, $product_id ) {
		$event_id   = absint( $event_id );
		$product_id = absint( $product_id );

		$ticket_id = self::get_bridge_ticket_id( $event_id, $product_id );

		if ( $ticket_id ) {
			return $ticket_id;
		}

		$ticket_id = self::get_first_event_ticket_id( $event_id );

		if ( $ticket_id ) {
			if ( $product_id ) {
				update_post_meta( $ticket_id, self::META_BRIDGE_PRODUCT_ID, $product_id );
			}

			return $ticket_id;
		}

		$module = tribe( \TEC\Tickets\Commerce\Module::class );

		if ( ! is_object( $module ) || ! method_exists( $module, 'ticket_add' ) ) {
			return 0;
		}

		$product = $product_id && function_exists( 'wc_get_product' ) ? wc_get_product( $product_id ) : false;
		$price   = $product instanceof WC_Product ? wc_format_decimal( $product->get_price(), wc_get_price_decimals() ) : '0';
		$title   = get_the_title( $event_id );
		$title   = '' !== (string) $title ? $title : __( 'GatiCrew Event', 'gaticrew-events-bridge' );

		// This creates a real Tickets Commerce ticket. It is only auto-created
		// when the event has no TEC ticket to use for attendee generation.
		$ticket_id = $module->ticket_add(
			$event_id,
			array(
				'ticket_name'             => sanitize_text_field( $title ),
				'ticket_description'      => __( 'Auto-created by GatiCrew Events Bridge for WooCommerce booking attendee generation.', 'gaticrew-events-bridge' ),
				'ticket_price'            => $price,
				'ticket_show_description' => 'no',
				'ticket_type'             => 'default',
				'tribe-ticket'            => array(
					// Empty mode keeps the generated ticket unlimited and avoids
					// blocking WooCommerce inventory as the source of sale truth.
					'mode'     => '',
					'capacity' => -1,
					'stock'    => -1,
				),
			)
		);

		$ticket_id = absint( $ticket_id );

		if ( $ticket_id ) {
			update_post_meta( $ticket_id, self::META_BRIDGE_TICKET, 'yes' );
			update_post_meta( $ticket_id, self::META_BRIDGE_PRODUCT_ID, $product_id );
			update_post_meta( $event_id, '_tribe_default_ticket_provider', \TEC\Tickets\Commerce\Module::class );
		}

		return $ticket_id;
	}

	/**
	 * Finds a bridge-managed ticket for the event/product pair.
	 *
	 * @param int $event_id Event post ID.
	 * @param int $product_id Linked product ID.
	 * @return int
	 */
	private static function get_bridge_ticket_id( $event_id, $product_id ) {
		$args = array(
			'post_type'              => \TEC\Tickets\Commerce\Ticket::POSTTYPE,
			'post_status'            => 'publish',
			'posts_per_page'         => 1,
			'fields'                 => 'ids',
			'no_found_rows'          => true,
			'update_post_meta_cache' => false,
			'update_post_term_cache' => false,
			'meta_query'             => array(
				'relation' => 'AND',
				array(
					'key'   => \TEC\Tickets\Commerce\Ticket::$event_relation_meta_key,
					'value' => absint( $event_id ),
				),
				array(
					'key'   => self::META_BRIDGE_PRODUCT_ID,
					'value' => absint( $product_id ),
				),
			),
		);

		$ids = get_posts( $args );

		return ! empty( $ids[0] ) ? absint( $ids[0] ) : 0;
	}

	/**
	 * Returns the first existing Tickets Commerce ticket for the event.
	 *
	 * @param int $event_id Event post ID.
	 * @return int
	 */
	private static function get_first_event_ticket_id( $event_id ) {
		$ids = get_posts(
			array(
				'post_type'              => \TEC\Tickets\Commerce\Ticket::POSTTYPE,
				'post_status'            => 'publish',
				'posts_per_page'         => 1,
				'fields'                 => 'ids',
				'no_found_rows'          => true,
				'update_post_meta_cache' => false,
				'update_post_term_cache' => false,
				'meta_query'             => array(
					array(
						'key'   => \TEC\Tickets\Commerce\Ticket::$event_relation_meta_key,
						'value' => absint( $event_id ),
					),
				),
			)
		);

		return ! empty( $ids[0] ) ? absint( $ids[0] ) : 0;
	}

	/**
	 * Creates one official Event Tickets attendee from the TEC ticket.
	 *
	 * @param int    $ticket_id Tickets Commerce ticket ID.
	 * @param string $name Attendee name.
	 * @param string $email Attendee email.
	 * @return WP_Post|WP_Error|false
	 */
	private static function create_event_tickets_attendee( $ticket_id, $name, $email ) {
		$module = tribe( \TEC\Tickets\Commerce\Module::class );

		if ( ! is_object( $module ) || ! method_exists( $module, 'create_attendee' ) ) {
			return new WP_Error( 'event_tickets_unavailable', __( 'Event Tickets attendee creation API is unavailable.', 'gaticrew-events-bridge' ) );
		}

		return $module->create_attendee(
			absint( $ticket_id ),
			array(
				'full_name'         => sanitize_text_field( $name ),
				'email'             => sanitize_email( $email ),
				'send_ticket_email' => false,
			)
		);
	}

	/**
	 * Adds bridge metadata to a TEC attendee without changing TEC-owned fields.
	 *
	 * @param int      $attendee_id Event Tickets attendee post ID.
	 * @param WC_Order $order WooCommerce order.
	 * @param string   $booking_id Booking ID.
	 * @param int      $event_id Event post ID.
	 * @param int      $product_id Woo product ID.
	 * @param int      $ticket_index Attendee index within booking.
	 * @param string   $attendee_name Attendee name.
	 * @param array    $customer Customer data.
	 * @return void
	 */
	private static function tag_attendee( $attendee_id, WC_Order $order, $booking_id, $event_id, $product_id, $ticket_index, $attendee_name, array $customer ) {
		$order_item_id = self::get_first_matching_order_item_id( $order, $product_id );

		update_post_meta( $attendee_id, self::META_BOOKING_ID, GatiCrew_Events_Bridge_Bookings::sanitize_booking_id( $booking_id ) );
		update_post_meta( $attendee_id, self::META_WOO_ORDER_ID, absint( $order->get_id() ) );
		update_post_meta( $attendee_id, self::META_WOO_ORDER_ITEM_ID, absint( $order_item_id ) );
		update_post_meta( $attendee_id, self::META_TICKET_INDEX, absint( $ticket_index ) );
		update_post_meta( $attendee_id, self::META_SOURCE_PRODUCT_ID, absint( $product_id ) );
		update_post_meta( $attendee_id, self::META_CUSTOMER_PHONE, sanitize_text_field( $customer['phone'] ) );
		update_post_meta( $attendee_id, '_tribe_tickets_full_name', sanitize_text_field( $attendee_name ) );
		update_post_meta( $attendee_id, '_tribe_tickets_email', sanitize_email( $customer['email'] ) );
	}

	/**
	 * Backfills official TEC attendee linkage for existing synced attendees.
	 *
	 * @param array    $attendee_ids TEC attendee post IDs.
	 * @param WC_Order $order WooCommerce order.
	 * @param string   $booking_id Booking ID.
	 * @param int      $event_id Event post ID.
	 * @return void
	 */
	private static function sync_existing_attendee_rows( array $attendee_ids, WC_Order $order, $booking_id, $event_id ) {
		foreach ( array_values( array_unique( array_map( 'absint', $attendee_ids ) ) ) as $index => $attendee_id ) {
			$ticket_index = absint( get_post_meta( $attendee_id, self::META_TICKET_INDEX, true ) );
			$ticket_index = $ticket_index ? $ticket_index : $index + 1;

			self::persist_tec_attendee_to_row( $attendee_id, $order, $booking_id, $ticket_index, $event_id );
		}
	}

	/**
	 * Saves official Event Tickets attendee QR data onto the matching bridge row.
	 *
	 * @param int      $attendee_id TEC attendee post ID.
	 * @param WC_Order $order WooCommerce order.
	 * @param string   $booking_id Booking ID.
	 * @param int      $ticket_index One-based ticket index.
	 * @param int      $event_id Event post ID.
	 * @return void
	 */
	private static function persist_tec_attendee_to_row( $attendee_id, WC_Order $order, $booking_id, $ticket_index, $event_id ) {
		if ( ! class_exists( 'GatiCrew_Events_Bridge_Attendees_Repository' ) ) {
			self::debug_log( 'Attendee repository unavailable while saving TEC attendee linkage.' );
			return;
		}

		$attendee_id = absint( $attendee_id );
		$event_id    = absint( $event_id );

		if ( ! $attendee_id || ! $event_id ) {
			return;
		}

		$data       = self::get_tec_attendee_link_data( $attendee_id, $event_id );
		$repository = new GatiCrew_Events_Bridge_Attendees_Repository();
		$row_id     = $repository->update_tec_ticket_data( absint( $order->get_id() ), $booking_id, $ticket_index, $data );

		self::debug_log(
			'Stored TEC attendee linkage: ' . wp_json_encode(
				array(
					'order_id'        => absint( $order->get_id() ),
					'booking_id'      => GatiCrew_Events_Bridge_Bookings::sanitize_booking_id( $booking_id ),
					'ticket_index'    => absint( $ticket_index ),
					'gaticrew_row_id' => absint( $row_id ),
					'tec_attendee_id' => $attendee_id,
					'security_code'   => $data['tec_security_code'],
					'qr_url'          => $data['tec_qr_url'],
					'qr_image_url'    => $data['tec_qr_image_url'],
				)
			)
		);
	}

	/**
	 * Builds a bridge row payload from official Event Tickets attendee meta.
	 *
	 * @param int $attendee_id TEC attendee post ID.
	 * @param int $event_id Event post ID.
	 * @return array
	 */
	private static function get_tec_attendee_link_data( $attendee_id, $event_id ) {
		$security_code = self::get_tec_attendee_security_code( $attendee_id );
		$qr_url        = self::get_tec_attendee_qr_url( $attendee_id, $event_id, $security_code );

		return array(
			'tec_attendee_post_id' => absint( $attendee_id ),
			'tec_security_code'    => $security_code,
			'tec_qr_url'           => $qr_url,
			'tec_qr_image_url'     => self::get_tec_attendee_qr_image_url( $qr_url ),
		);
	}

	/**
	 * Reads TEC's official stored attendee security code.
	 *
	 * @param int $attendee_id TEC attendee post ID.
	 * @return string
	 */
	private static function get_tec_attendee_security_code( $attendee_id ) {
		$keys = array( '_tec_tickets_commerce_security_code', '_tribe_wooticket_security_code', '_tribe_rsvp_security_code', '_tribe_tpp_security_code', '_tribe_tickets_security_code' );

		if ( class_exists( '\TEC\Tickets\Commerce\Attendee' ) ) {
			array_unshift( $keys, \TEC\Tickets\Commerce\Attendee::$security_code_meta_key );
		}

		foreach ( array_unique( $keys ) as $key ) {
			$value = get_post_meta( absint( $attendee_id ), sanitize_text_field( $key ), true );

			if ( '' !== (string) $value ) {
				return sanitize_text_field( $value );
			}
		}

		return '';
	}

	/**
	 * Builds TEC's official check-in URL through the QR connector.
	 *
	 * @param int    $attendee_id TEC attendee post ID.
	 * @param int    $event_id Event post ID.
	 * @param string $security_code TEC security code.
	 * @return string
	 */
	private static function get_tec_attendee_qr_url( $attendee_id, $event_id, $security_code ) {
		if ( ! function_exists( 'tribe' ) || ! class_exists( '\TEC\Tickets\QR\Connector' ) || '' === (string) $security_code ) {
			return '';
		}

		try {
			$connector = tribe( \TEC\Tickets\QR\Connector::class );

			if ( is_object( $connector ) && method_exists( $connector, 'get_checkin_url' ) ) {
				return esc_url_raw( $connector->get_checkin_url( absint( $attendee_id ), absint( $event_id ), sanitize_text_field( $security_code ) ) );
			}
		} catch ( Throwable $exception ) {
			self::debug_log( 'Unable to build TEC QR URL: ' . $exception->getMessage() );
		}

		return '';
	}

	/**
	 * Builds TEC's QR image URL for an official check-in URL.
	 *
	 * @param string $qr_url TEC check-in URL.
	 * @return string
	 */
	private static function get_tec_attendee_qr_image_url( $qr_url ) {
		if ( ! function_exists( 'tribe' ) || ! class_exists( '\TEC\Tickets\QR\Connector' ) || '' === (string) $qr_url ) {
			return '';
		}

		try {
			$connector = tribe( \TEC\Tickets\QR\Connector::class );

			if ( is_object( $connector ) && method_exists( $connector, 'get_image_url_for_link' ) ) {
				$image_url = $connector->get_image_url_for_link( esc_url_raw( $qr_url ) );

				return $image_url ? esc_url_raw( $image_url ) : '';
			}
		} catch ( Throwable $exception ) {
			self::debug_log( 'Unable to build TEC QR image URL: ' . $exception->getMessage() );
		}

		return '';
	}

	/**
	 * Finds all bridge-linked TEC attendees for this Woo order/booking.
	 *
	 * @param int    $order_id Woo order ID.
	 * @param string $booking_id Booking ID.
	 * @param int    $event_id Event ID.
	 * @return array
	 */
	private static function get_existing_attendee_ids( $order_id, $booking_id, $event_id ) {
		$args = array(
			'post_type'              => \TEC\Tickets\Commerce\Attendee::POSTTYPE,
			'post_status'            => 'publish',
			'posts_per_page'         => -1,
			'fields'                 => 'ids',
			'orderby'                => 'ID',
			'order'                  => 'ASC',
			'no_found_rows'          => true,
			'update_post_meta_cache' => false,
			'update_post_term_cache' => false,
			'meta_query'             => array(
				'relation' => 'AND',
				array(
					'key'   => self::META_WOO_ORDER_ID,
					'value' => absint( $order_id ),
				),
				array(
					'key'   => self::META_BOOKING_ID,
					'value' => GatiCrew_Events_Bridge_Bookings::sanitize_booking_id( $booking_id ),
				),
				array(
					'key'   => \TEC\Tickets\Commerce\Attendee::$event_relation_meta_key,
					'value' => absint( $event_id ),
				),
			),
		);

		return array_map( 'absint', get_posts( $args ) );
	}

	/**
	 * Finds an existing bridge-linked TEC attendee for one ticket index.
	 *
	 * @param int    $order_id Woo order ID.
	 * @param string $booking_id Booking ID.
	 * @param int    $ticket_index Attendee index.
	 * @return int
	 */
	private static function get_existing_attendee_id_for_index( $order_id, $booking_id, $ticket_index ) {
		$ids = get_posts(
			array(
				'post_type'              => \TEC\Tickets\Commerce\Attendee::POSTTYPE,
				'post_status'            => 'publish',
				'posts_per_page'         => 1,
				'fields'                 => 'ids',
				'no_found_rows'          => true,
				'update_post_meta_cache' => false,
				'update_post_term_cache' => false,
				'meta_query'             => array(
					'relation' => 'AND',
					array(
						'key'   => self::META_WOO_ORDER_ID,
						'value' => absint( $order_id ),
					),
					array(
						'key'   => self::META_BOOKING_ID,
						'value' => GatiCrew_Events_Bridge_Bookings::sanitize_booking_id( $booking_id ),
					),
					array(
						'key'   => self::META_TICKET_INDEX,
						'value' => absint( $ticket_index ),
					),
				),
			)
		);

		return ! empty( $ids[0] ) ? absint( $ids[0] ) : 0;
	}

	/**
	 * Returns the bridge booking ID stored on the order.
	 *
	 * @param WC_Order $order Woo order.
	 * @return string
	 */
	private static function get_order_booking_id( WC_Order $order ) {
		$booking_id = GatiCrew_Events_Bridge_Bookings::sanitize_booking_id( $order->get_meta( self::get_order_meta_key( 'ORDER_META_BOOKING_ID', '_gaticrew_booking_id' ), true ) );

		if ( '' !== $booking_id ) {
			return $booking_id;
		}

		foreach ( $order->get_items( 'line_item' ) as $item ) {
			if ( $item instanceof WC_Order_Item_Product ) {
				$booking_id = GatiCrew_Events_Bridge_Bookings::sanitize_booking_id( $item->get_meta( '_gaticrew_booking_id', true ) );

				if ( '' !== $booking_id ) {
					return $booking_id;
				}
			}
		}

		return '';
	}

	/**
	 * Returns the event ID stored on the order or inferred from linked product.
	 *
	 * @param WC_Order $order Woo order.
	 * @return int
	 */
	private static function get_order_event_id( WC_Order $order ) {
		$event_id = absint( $order->get_meta( self::get_order_meta_key( 'ORDER_META_EVENT_ID', '_gaticrew_event_id' ), true ) );

		if ( $event_id ) {
			return $event_id;
		}

		foreach ( $order->get_items( 'line_item' ) as $item ) {
			if ( ! $item instanceof WC_Order_Item_Product ) {
				continue;
			}

			$product_id = self::get_item_product_id( $item );
			$event_id   = self::get_event_id_by_product_id( $product_id );

			if ( $event_id ) {
				return $event_id;
			}
		}

		return 0;
	}

	/**
	 * Returns the linked Woo product ID for the order's event.
	 *
	 * @param WC_Order $order Woo order.
	 * @param int      $event_id Event ID.
	 * @return int
	 */
	private static function get_order_product_id( WC_Order $order, $event_id ) {
		foreach ( $order->get_items( 'line_item' ) as $item ) {
			if ( ! $item instanceof WC_Order_Item_Product ) {
				continue;
			}

			$product_id      = self::get_item_product_id( $item );
			$linked_event_id = self::get_event_id_by_product_id( $product_id );

			if ( $linked_event_id && absint( $event_id ) === $linked_event_id ) {
				return $product_id;
			}
		}

		return absint( get_post_meta( absint( $event_id ), self::get_event_product_meta_key(), true ) );
	}

	/**
	 * Returns total quantity for linked event items on the order.
	 *
	 * @param WC_Order $order Woo order.
	 * @param int      $event_id Event ID.
	 * @return int
	 */
	private static function get_order_quantity( WC_Order $order, $event_id ) {
		$quantity = absint( $order->get_meta( '_gaticrew_quantity', true ) );

		if ( $quantity ) {
			return $quantity;
		}

		$total = 0;

		foreach ( $order->get_items( 'line_item' ) as $item ) {
			if ( ! $item instanceof WC_Order_Item_Product ) {
				continue;
			}

			$product_id      = self::get_item_product_id( $item );
			$linked_event_id = self::get_event_id_by_product_id( $product_id );

			if ( absint( $event_id ) === $linked_event_id ) {
				$total += absint( $item->get_quantity() );
			}
		}

		return $total;
	}

	/**
	 * Returns attendee names saved on order or line item meta.
	 *
	 * @param WC_Order $order Woo order.
	 * @param int      $quantity Ticket quantity.
	 * @param string   $fallback_name Fallback customer name.
	 * @return array
	 */
	private static function get_order_attendee_names( WC_Order $order, $quantity, $fallback_name ) {
		$names = self::normalize_names_value( $order->get_meta( self::get_order_meta_key( 'ORDER_META_ATTENDEE_NAMES', '_gaticrew_attendee_names' ), true ) );

		if ( empty( $names ) ) {
			foreach ( $order->get_items( 'line_item' ) as $item ) {
				if ( ! $item instanceof WC_Order_Item_Product ) {
					continue;
				}

				$names = self::normalize_names_value( $item->get_meta( '_gaticrew_attendee_names', true ) );

				if ( ! empty( $names ) ) {
					break;
				}
			}
		}

		while ( count( $names ) < absint( $quantity ) ) {
			$names[] = sanitize_text_field( $fallback_name );
		}

		return array_slice( array_values( $names ), 0, absint( $quantity ) );
	}

	/**
	 * Normalizes stored attendee name values.
	 *
	 * @param mixed $value Raw order meta.
	 * @return array
	 */
	private static function normalize_names_value( $value ) {
		$value = maybe_unserialize( $value );

		if ( is_string( $value ) ) {
			$decoded = json_decode( $value, true );
			$value   = is_array( $decoded ) ? $decoded : array( $value );
		}

		if ( ! is_array( $value ) ) {
			return array();
		}

		$names = array();

		foreach ( $value as $name ) {
			$name = sanitize_text_field( $name );

			if ( '' !== $name ) {
				$names[] = $name;
			}
		}

		return array_values( $names );
	}

	/**
	 * Returns customer details from order billing/meta.
	 *
	 * @param WC_Order $order Woo order.
	 * @return array
	 */
	private static function get_customer_data( WC_Order $order ) {
		$name = trim( $order->get_formatted_billing_full_name() );

		if ( '' === $name ) {
			$name = sanitize_text_field( (string) $order->get_meta( self::get_order_meta_key( 'ORDER_META_CUSTOMER_NAME', '_gaticrew_customer_name' ), true ) );
		}

		$email = $order->get_billing_email();

		if ( '' === $email ) {
			$email = $order->get_meta( self::get_order_meta_key( 'ORDER_META_CUSTOMER_EMAIL', '_gaticrew_customer_email' ), true );
		}

		$phone = $order->get_billing_phone();

		if ( '' === $phone ) {
			$phone = $order->get_meta( self::get_order_meta_key( 'ORDER_META_CUSTOMER_PHONE', '_gaticrew_customer_phone' ), true );
		}

		return array(
			'name'  => '' !== $name ? sanitize_text_field( $name ) : __( 'Guest', 'gaticrew-events-bridge' ),
			'email' => sanitize_email( $email ),
			'phone' => function_exists( 'wc_sanitize_phone_number' ) ? wc_sanitize_phone_number( $phone ) : sanitize_text_field( $phone ),
		);
	}

	/**
	 * Finds a linked event by Woo product ID.
	 *
	 * @param int $product_id Woo product ID.
	 * @return int
	 */
	private static function get_event_id_by_product_id( $product_id ) {
		$product_id = absint( $product_id );

		if ( ! $product_id ) {
			return 0;
		}

		$events = get_posts(
			array(
				'post_type'              => class_exists( 'GatiCrew_Events_Bridge_Events' ) ? GatiCrew_Events_Bridge_Events::get_event_post_type() : 'tribe_events',
				'post_status'            => 'publish',
				'posts_per_page'         => 1,
				'fields'                 => 'ids',
				'no_found_rows'          => true,
				'update_post_meta_cache' => false,
				'update_post_term_cache' => false,
				'meta_query'             => array(
					'relation' => 'OR',
					array(
						'key'     => '_gaticrew_product_id',
						'value'   => $product_id,
						'compare' => '=',
						'type'    => 'NUMERIC',
					),
					array(
						'key'     => self::get_event_product_meta_key(),
						'value'   => $product_id,
						'compare' => '=',
						'type'    => 'NUMERIC',
					),
				),
			)
		);

		return ! empty( $events[0] ) ? absint( $events[0] ) : 0;
	}

	/**
	 * Returns product ID from an order line.
	 *
	 * @param WC_Order_Item_Product $item Order item.
	 * @return int
	 */
	private static function get_item_product_id( WC_Order_Item_Product $item ) {
		return absint( $item->get_variation_id() ? $item->get_variation_id() : $item->get_product_id() );
	}

	/**
	 * Finds the first line item ID matching the linked product.
	 *
	 * @param WC_Order $order Woo order.
	 * @param int      $product_id Woo product ID.
	 * @return int
	 */
	private static function get_first_matching_order_item_id( WC_Order $order, $product_id ) {
		foreach ( $order->get_items( 'line_item' ) as $item_id => $item ) {
			if ( $item instanceof WC_Order_Item_Product && absint( $product_id ) === self::get_item_product_id( $item ) ) {
				return absint( $item_id );
			}
		}

		return 0;
	}

	/**
	 * Returns the event/product meta key used by this plugin.
	 *
	 * @return string
	 */
	private static function get_event_product_meta_key() {
		return class_exists( 'GatiCrew_Events_Bridge' ) && defined( 'GatiCrew_Events_Bridge::META_KEY_TICKET_PRODUCT_ID' )
			? GatiCrew_Events_Bridge::META_KEY_TICKET_PRODUCT_ID
			: '_gaticrew_ticket_product_id';
	}

	/**
	 * Returns an order meta key with fallback for early REST contexts.
	 *
	 * @param string $constant Class constant name.
	 * @param string $fallback Fallback meta key.
	 * @return string
	 */
	private static function get_order_meta_key( $constant, $fallback ) {
		return class_exists( 'GatiCrew_Events_Bridge' ) && defined( 'GatiCrew_Events_Bridge::' . $constant )
			? constant( 'GatiCrew_Events_Bridge::' . $constant )
			: $fallback;
	}

	/**
	 * Writes sync diagnostics to the PHP error log.
	 *
	 * @param string $message Message.
	 * @return void
	 */
	private static function debug_log( $message ) {
		error_log( '[GatiCrew Event Tickets Sync] ' . (string) $message ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log -- Temporary diagnostics for attendee sync.
	}

	/**
	 * Prevent instantiation.
	 */
	private function __construct() {}
}
