<?php
/**
 * Lightweight QR Code SVG generator.
 *
 * This intentionally avoids third-party packages. It supports byte-mode QR
 * symbols up to version 10 with low error correction, which is more than
 * enough for the short secure check-in URLs generated by this plugin.
 *
 * @package GatiCrew_Events_Bridge
 */

defined( 'ABSPATH' ) || exit;

final class GatiCrew_Events_Bridge_QR_Code {
	/**
	 * Version metadata for QR Code error correction level L.
	 *
	 * @var array
	 */
	private static $versions = array(
		1  => array( 'ec' => 7,  'blocks' => array( array( 'count' => 1, 'data' => 19 ) ) ),
		2  => array( 'ec' => 10, 'blocks' => array( array( 'count' => 1, 'data' => 34 ) ) ),
		3  => array( 'ec' => 15, 'blocks' => array( array( 'count' => 1, 'data' => 55 ) ) ),
		4  => array( 'ec' => 20, 'blocks' => array( array( 'count' => 1, 'data' => 80 ) ) ),
		5  => array( 'ec' => 26, 'blocks' => array( array( 'count' => 1, 'data' => 108 ) ) ),
		6  => array( 'ec' => 18, 'blocks' => array( array( 'count' => 2, 'data' => 68 ) ) ),
		7  => array( 'ec' => 20, 'blocks' => array( array( 'count' => 2, 'data' => 78 ) ) ),
		8  => array( 'ec' => 24, 'blocks' => array( array( 'count' => 2, 'data' => 97 ) ) ),
		9  => array( 'ec' => 30, 'blocks' => array( array( 'count' => 2, 'data' => 116 ) ) ),
		10 => array( 'ec' => 18, 'blocks' => array( array( 'count' => 2, 'data' => 68 ), array( 'count' => 2, 'data' => 69 ) ) ),
	);

	/**
	 * Alignment pattern positions by version.
	 *
	 * @var array
	 */
	private static $alignment_positions = array(
		1  => array(),
		2  => array( 6, 18 ),
		3  => array( 6, 22 ),
		4  => array( 6, 26 ),
		5  => array( 6, 30 ),
		6  => array( 6, 34 ),
		7  => array( 6, 22, 38 ),
		8  => array( 6, 24, 42 ),
		9  => array( 6, 26, 46 ),
		10 => array( 6, 28, 50 ),
	);

	/**
	 * Galios field exponent table.
	 *
	 * @var array|null
	 */
	private static $gf_exp = null;

	/**
	 * Galios field log table.
	 *
	 * @var array|null
	 */
	private static $gf_log = null;

	/**
	 * Generates a QR code SVG string for the supplied content.
	 *
	 * @param string $content QR payload.
	 * @param int    $scale Module scale.
	 * @param int    $border Quiet-zone modules.
	 * @return string
	 */
	public static function render_svg( $content, $scale = 6, $border = 4 ) {
		$matrix = self::encode( $content );
		$size   = count( $matrix );
		$scale  = max( 2, absint( $scale ) );
		$border = max( 4, absint( $border ) );
		$view   = $size + ( $border * 2 );
		$path   = '';

		for ( $y = 0; $y < $size; $y++ ) {
			for ( $x = 0; $x < $size; $x++ ) {
				if ( ! empty( $matrix[ $y ][ $x ] ) ) {
					$path .= 'M' . ( $x + $border ) . ',' . ( $y + $border ) . 'h1v1h-1z';
				}
			}
		}

		return sprintf(
			'<svg xmlns="http://www.w3.org/2000/svg" width="%1$d" height="%1$d" viewBox="0 0 %2$d %2$d" role="img" aria-label="%3$s" shape-rendering="crispEdges"><rect width="100%%" height="100%%" fill="#fff"/><path d="%4$s" fill="#111827"/></svg>',
			$view * $scale,
			$view,
			esc_attr__( 'GatiCrew QR ticket', 'gaticrew-events-bridge' ),
			esc_attr( $path )
		);
	}

	/**
	 * Encodes content into a boolean module matrix.
	 *
	 * @param string $content QR payload.
	 * @return array
	 */
	private static function encode( $content ) {
		$bytes   = array_values( unpack( 'C*', (string) $content ) );
		$version = self::choose_version( count( $bytes ) );
		$size    = ( $version * 4 ) + 17;
		$modules = array();
		$is_func = array();

		for ( $y = 0; $y < $size; $y++ ) {
			$modules[ $y ] = array_fill( 0, $size, false );
			$is_func[ $y ] = array_fill( 0, $size, false );
		}

		self::draw_function_patterns( $modules, $is_func, $version );
		self::draw_codewords( $modules, $is_func, self::create_codewords( $bytes, $version ) );

		$best_matrix  = null;
		$best_penalty = PHP_INT_MAX;
		$best_mask    = 0;

		for ( $mask = 0; $mask < 8; $mask++ ) {
			$test = $modules;
			self::apply_mask( $test, $is_func, $mask );
			self::draw_format_bits( $test, $is_func, $mask );

			if ( $version >= 7 ) {
				self::draw_version_bits( $test, $is_func, $version );
			}

			$penalty = self::get_penalty_score( $test );

			if ( $penalty < $best_penalty ) {
				$best_penalty = $penalty;
				$best_matrix  = $test;
				$best_mask    = $mask;
			}
		}

		unset( $best_mask );

		return $best_matrix;
	}

	/**
	 * Selects the smallest supported QR version for the payload.
	 *
	 * @param int $byte_count Payload byte length.
	 * @return int
	 */
	private static function choose_version( $byte_count ) {
		foreach ( self::$versions as $version => $info ) {
			$count_bits = $version <= 9 ? 8 : 16;
			$capacity   = self::get_data_codeword_count( $version ) * 8;
			$needed     = 4 + $count_bits + ( $byte_count * 8 );

			if ( $needed <= $capacity ) {
				return $version;
			}
		}

		throw new InvalidArgumentException( 'QR payload is too long for the supported encoder.' );
	}

	/**
	 * Creates interleaved data and Reed-Solomon error correction codewords.
	 *
	 * @param array $bytes Payload bytes.
	 * @param int   $version QR version.
	 * @return array
	 */
	private static function create_codewords( array $bytes, $version ) {
		$data_count = self::get_data_codeword_count( $version );
		$bits       = array();

		self::append_bits( $bits, 0x4, 4 );
		self::append_bits( $bits, count( $bytes ), $version <= 9 ? 8 : 16 );

		foreach ( $bytes as $byte ) {
			self::append_bits( $bits, $byte, 8 );
		}

		$capacity = $data_count * 8;
		$terminator = min( 4, $capacity - count( $bits ) );

		self::append_bits( $bits, 0, $terminator );

		while ( 0 !== count( $bits ) % 8 ) {
			$bits[] = false;
		}

		$pad_byte = 0xec;

		while ( count( $bits ) < $capacity ) {
			self::append_bits( $bits, $pad_byte, 8 );
			$pad_byte = 0xec === $pad_byte ? 0x11 : 0xec;
		}

		$data = array();

		for ( $i = 0; $i < count( $bits ); $i += 8 ) {
			$value = 0;

			for ( $j = 0; $j < 8; $j++ ) {
				$value = ( $value << 1 ) | ( $bits[ $i + $j ] ? 1 : 0 );
			}

			$data[] = $value;
		}

		return self::add_error_correction( $data, $version );
	}

	/**
	 * Adds Reed-Solomon error correction and interleaves blocks.
	 *
	 * @param array $data_codewords Data codewords.
	 * @param int   $version QR version.
	 * @return array
	 */
	private static function add_error_correction( array $data_codewords, $version ) {
		$info       = self::$versions[ $version ];
		$ec_length  = $info['ec'];
		$blocks     = array();
		$data_index = 0;
		$max_data   = 0;

		foreach ( $info['blocks'] as $group ) {
			for ( $i = 0; $i < $group['count']; $i++ ) {
				$data = array_slice( $data_codewords, $data_index, $group['data'] );
				$data_index += $group['data'];
				$blocks[] = array(
					'data' => $data,
					'ec'   => self::reed_solomon_remainder( $data, $ec_length ),
				);
				$max_data = max( $max_data, count( $data ) );
			}
		}

		$result = array();

		for ( $i = 0; $i < $max_data; $i++ ) {
			foreach ( $blocks as $block ) {
				if ( array_key_exists( $i, $block['data'] ) ) {
					$result[] = $block['data'][ $i ];
				}
			}
		}

		for ( $i = 0; $i < $ec_length; $i++ ) {
			foreach ( $blocks as $block ) {
				$result[] = $block['ec'][ $i ];
			}
		}

		return $result;
	}

	/**
	 * Draws finder, timing, alignment, version, and reserved format modules.
	 *
	 * @param array $modules Matrix.
	 * @param array $is_func Function-module matrix.
	 * @param int   $version QR version.
	 * @return void
	 */
	private static function draw_function_patterns( array &$modules, array &$is_func, $version ) {
		$size = count( $modules );

		self::draw_finder_pattern( $modules, $is_func, 0, 0 );
		self::draw_finder_pattern( $modules, $is_func, $size - 7, 0 );
		self::draw_finder_pattern( $modules, $is_func, 0, $size - 7 );

		for ( $i = 8; $i < $size - 8; $i++ ) {
			$dark = 0 === $i % 2;
			self::set_function_module( $modules, $is_func, 6, $i, $dark );
			self::set_function_module( $modules, $is_func, $i, 6, $dark );
		}

		foreach ( self::$alignment_positions[ $version ] as $x ) {
			foreach ( self::$alignment_positions[ $version ] as $y ) {
				if ( $is_func[ $y ][ $x ] ) {
					continue;
				}

				self::draw_alignment_pattern( $modules, $is_func, $x, $y );
			}
		}

		self::draw_format_bits( $modules, $is_func, 0 );
		self::set_function_module( $modules, $is_func, 8, $size - 8, true );

		if ( $version >= 7 ) {
			self::draw_version_bits( $modules, $is_func, $version );
		}
	}

	/**
	 * Draws a finder pattern and its separator.
	 *
	 * @param array $modules Matrix.
	 * @param array $is_func Function-module matrix.
	 * @param int   $left Left coordinate.
	 * @param int   $top Top coordinate.
	 * @return void
	 */
	private static function draw_finder_pattern( array &$modules, array &$is_func, $left, $top ) {
		$size = count( $modules );

		for ( $dy = -1; $dy <= 7; $dy++ ) {
			for ( $dx = -1; $dx <= 7; $dx++ ) {
				$x = $left + $dx;
				$y = $top + $dy;

				if ( $x < 0 || $x >= $size || $y < 0 || $y >= $size ) {
					continue;
				}

				$is_core = $dx >= 0 && $dx <= 6 && $dy >= 0 && $dy <= 6;
				$dark    = $is_core && ( 0 === $dx || 6 === $dx || 0 === $dy || 6 === $dy || ( $dx >= 2 && $dx <= 4 && $dy >= 2 && $dy <= 4 ) );

				self::set_function_module( $modules, $is_func, $x, $y, $dark );
			}
		}
	}

	/**
	 * Draws an alignment pattern.
	 *
	 * @param array $modules Matrix.
	 * @param array $is_func Function-module matrix.
	 * @param int   $center_x Center X.
	 * @param int   $center_y Center Y.
	 * @return void
	 */
	private static function draw_alignment_pattern( array &$modules, array &$is_func, $center_x, $center_y ) {
		for ( $dy = -2; $dy <= 2; $dy++ ) {
			for ( $dx = -2; $dx <= 2; $dx++ ) {
				$dark = 2 === max( abs( $dx ), abs( $dy ) ) || ( 0 === $dx && 0 === $dy );
				self::set_function_module( $modules, $is_func, $center_x + $dx, $center_y + $dy, $dark );
			}
		}
	}

	/**
	 * Draws final codeword bits into data modules.
	 *
	 * @param array $modules Matrix.
	 * @param array $is_func Function-module matrix.
	 * @param array $codewords Final codewords.
	 * @return void
	 */
	private static function draw_codewords( array &$modules, array $is_func, array $codewords ) {
		$bits = array();

		foreach ( $codewords as $codeword ) {
			for ( $i = 7; $i >= 0; $i-- ) {
				$bits[] = 1 === ( ( $codeword >> $i ) & 1 );
			}
		}

		$size      = count( $modules );
		$bit_index = 0;
		$upward    = true;

		for ( $right = $size - 1; $right >= 1; $right -= 2 ) {
			if ( 6 === $right ) {
				$right--;
			}

			for ( $vertical = 0; $vertical < $size; $vertical++ ) {
				$y = $upward ? $size - 1 - $vertical : $vertical;

				for ( $j = 0; $j < 2; $j++ ) {
					$x = $right - $j;

					if ( $is_func[ $y ][ $x ] ) {
						continue;
					}

					$modules[ $y ][ $x ] = isset( $bits[ $bit_index ] ) ? $bits[ $bit_index ] : false;
					$bit_index++;
				}
			}

			$upward = ! $upward;
		}
	}

	/**
	 * Applies one of the eight QR masks to data modules.
	 *
	 * @param array $modules Matrix.
	 * @param array $is_func Function-module matrix.
	 * @param int   $mask Mask number.
	 * @return void
	 */
	private static function apply_mask( array &$modules, array $is_func, $mask ) {
		$size = count( $modules );

		for ( $y = 0; $y < $size; $y++ ) {
			for ( $x = 0; $x < $size; $x++ ) {
				if ( $is_func[ $y ][ $x ] ) {
					continue;
				}

				if ( self::mask_condition( $mask, $x, $y ) ) {
					$modules[ $y ][ $x ] = ! $modules[ $y ][ $x ];
				}
			}
		}
	}

	/**
	 * Returns whether a mask flips the current coordinate.
	 *
	 * @param int $mask Mask number.
	 * @param int $x X coordinate.
	 * @param int $y Y coordinate.
	 * @return bool
	 */
	private static function mask_condition( $mask, $x, $y ) {
		switch ( $mask ) {
			case 0:
				return 0 === ( $x + $y ) % 2;
			case 1:
				return 0 === $y % 2;
			case 2:
				return 0 === $x % 3;
			case 3:
				return 0 === ( $x + $y ) % 3;
			case 4:
				return 0 === ( intdiv( $y, 2 ) + intdiv( $x, 3 ) ) % 2;
			case 5:
				return 0 === ( ( $x * $y ) % 2 ) + ( ( $x * $y ) % 3 );
			case 6:
				return 0 === ( ( ( $x * $y ) % 2 ) + ( ( $x * $y ) % 3 ) ) % 2;
			case 7:
				return 0 === ( ( ( $x + $y ) % 2 ) + ( ( $x * $y ) % 3 ) ) % 2;
			default:
				return false;
		}
	}

	/**
	 * Draws format bits for error correction level L and selected mask.
	 *
	 * @param array $modules Matrix.
	 * @param array $is_func Function-module matrix.
	 * @param int   $mask Mask number.
	 * @return void
	 */
	private static function draw_format_bits( array &$modules, array &$is_func, $mask ) {
		$size = count( $modules );
		$data = ( 1 << 3 ) | $mask;
		$bits = self::get_format_bits( $data );

		for ( $i = 0; $i < 15; $i++ ) {
			$dark = 1 === ( ( $bits >> $i ) & 1 );

			if ( $i < 6 ) {
				self::set_function_module( $modules, $is_func, 8, $i, $dark );
			} elseif ( $i < 8 ) {
				self::set_function_module( $modules, $is_func, 8, $i + 1, $dark );
			} elseif ( 8 === $i ) {
				self::set_function_module( $modules, $is_func, 7, 8, $dark );
			} else {
				self::set_function_module( $modules, $is_func, 14 - $i, 8, $dark );
			}

			if ( $i < 8 ) {
				self::set_function_module( $modules, $is_func, $size - 1 - $i, 8, $dark );
			} else {
				self::set_function_module( $modules, $is_func, 8, $size - 15 + $i, $dark );
			}
		}
	}

	/**
	 * Computes 15-bit QR format information.
	 *
	 * @param int $data Format data.
	 * @return int
	 */
	private static function get_format_bits( $data ) {
		$rem = $data << 10;

		for ( $i = 14; $i >= 10; $i-- ) {
			if ( 0 !== ( ( $rem >> $i ) & 1 ) ) {
				$rem ^= 0x537 << ( $i - 10 );
			}
		}

		return ( ( $data << 10 ) | $rem ) ^ 0x5412;
	}

	/**
	 * Draws version bits for version 7 and above.
	 *
	 * @param array $modules Matrix.
	 * @param array $is_func Function-module matrix.
	 * @param int   $version QR version.
	 * @return void
	 */
	private static function draw_version_bits( array &$modules, array &$is_func, $version ) {
		$size = count( $modules );
		$rem  = $version;

		for ( $i = 0; $i < 12; $i++ ) {
			$rem = ( $rem << 1 ) ^ ( ( ( $rem >> 11 ) & 1 ) ? 0x1f25 : 0 );
		}

		$bits = ( $version << 12 ) | $rem;

		for ( $i = 0; $i < 18; $i++ ) {
			$dark = 1 === ( ( $bits >> $i ) & 1 );
			$x    = $size - 11 + ( $i % 3 );
			$y    = intdiv( $i, 3 );

			self::set_function_module( $modules, $is_func, $x, $y, $dark );
			self::set_function_module( $modules, $is_func, $y, $x, $dark );
		}
	}

	/**
	 * Sets a function module.
	 *
	 * @param array $modules Matrix.
	 * @param array $is_func Function-module matrix.
	 * @param int   $x X coordinate.
	 * @param int   $y Y coordinate.
	 * @param bool  $dark Dark module flag.
	 * @return void
	 */
	private static function set_function_module( array &$modules, array &$is_func, $x, $y, $dark ) {
		$size = count( $modules );

		if ( $x < 0 || $x >= $size || $y < 0 || $y >= $size ) {
			return;
		}

		$modules[ $y ][ $x ] = (bool) $dark;
		$is_func[ $y ][ $x ] = true;
	}

	/**
	 * Appends bits MSB first.
	 *
	 * @param array $bits Bit buffer.
	 * @param int   $value Value.
	 * @param int   $length Bit length.
	 * @return void
	 */
	private static function append_bits( array &$bits, $value, $length ) {
		for ( $i = $length - 1; $i >= 0; $i-- ) {
			$bits[] = 1 === ( ( $value >> $i ) & 1 );
		}
	}

	/**
	 * Returns total data codewords for a QR version.
	 *
	 * @param int $version QR version.
	 * @return int
	 */
	private static function get_data_codeword_count( $version ) {
		$total = 0;

		foreach ( self::$versions[ $version ]['blocks'] as $group ) {
			$total += $group['count'] * $group['data'];
		}

		return $total;
	}

	/**
	 * Computes Reed-Solomon remainder.
	 *
	 * @param array $data Data codewords.
	 * @param int   $degree ECC degree.
	 * @return array
	 */
	private static function reed_solomon_remainder( array $data, $degree ) {
		$divisor = self::reed_solomon_divisor( $degree );
		$result  = array_fill( 0, $degree, 0 );

		foreach ( $data as $byte ) {
			$factor = $byte ^ $result[0];
			array_shift( $result );
			$result[] = 0;

			for ( $i = 0; $i < $degree; $i++ ) {
				$result[ $i ] ^= self::gf_multiply( $divisor[ $i ], $factor );
			}
		}

		return $result;
	}

	/**
	 * Computes Reed-Solomon divisor polynomial coefficients.
	 *
	 * @param int $degree ECC degree.
	 * @return array
	 */
	private static function reed_solomon_divisor( $degree ) {
		self::init_gf_tables();

		$result = array_fill( 0, $degree, 0 );
		$result[ $degree - 1 ] = 1;
		$root = 1;

		for ( $i = 0; $i < $degree; $i++ ) {
			for ( $j = 0; $j < $degree; $j++ ) {
				$result[ $j ] = self::gf_multiply( $result[ $j ], $root );

				if ( $j + 1 < $degree ) {
					$result[ $j ] ^= $result[ $j + 1 ];
				}
			}

			$root = self::gf_multiply( $root, 0x02 );
		}

		return $result;
	}

	/**
	 * Multiplies two GF(256) values.
	 *
	 * @param int $x First value.
	 * @param int $y Second value.
	 * @return int
	 */
	private static function gf_multiply( $x, $y ) {
		self::init_gf_tables();

		if ( 0 === $x || 0 === $y ) {
			return 0;
		}

		return self::$gf_exp[ self::$gf_log[ $x ] + self::$gf_log[ $y ] ];
	}

	/**
	 * Initializes GF(256) lookup tables.
	 *
	 * @return void
	 */
	private static function init_gf_tables() {
		if ( null !== self::$gf_exp && null !== self::$gf_log ) {
			return;
		}

		self::$gf_exp = array_fill( 0, 512, 0 );
		self::$gf_log = array_fill( 0, 256, 0 );

		$x = 1;

		for ( $i = 0; $i < 255; $i++ ) {
			self::$gf_exp[ $i ] = $x;
			self::$gf_log[ $x ] = $i;
			$x <<= 1;

			if ( 0 !== ( $x & 0x100 ) ) {
				$x ^= 0x11d;
			}
		}

		for ( $i = 255; $i < 512; $i++ ) {
			self::$gf_exp[ $i ] = self::$gf_exp[ $i - 255 ];
		}
	}

	/**
	 * Calculates QR mask penalty score.
	 *
	 * @param array $modules Matrix.
	 * @return int
	 */
	private static function get_penalty_score( array $modules ) {
		$size    = count( $modules );
		$penalty = 0;

		for ( $y = 0; $y < $size; $y++ ) {
			$run_color = $modules[ $y ][0];
			$run       = 1;

			for ( $x = 1; $x < $size; $x++ ) {
				if ( $modules[ $y ][ $x ] === $run_color ) {
					$run++;
				} else {
					if ( $run >= 5 ) {
						$penalty += 3 + ( $run - 5 );
					}
					$run_color = $modules[ $y ][ $x ];
					$run       = 1;
				}
			}

			if ( $run >= 5 ) {
				$penalty += 3 + ( $run - 5 );
			}
		}

		for ( $x = 0; $x < $size; $x++ ) {
			$run_color = $modules[0][ $x ];
			$run       = 1;

			for ( $y = 1; $y < $size; $y++ ) {
				if ( $modules[ $y ][ $x ] === $run_color ) {
					$run++;
				} else {
					if ( $run >= 5 ) {
						$penalty += 3 + ( $run - 5 );
					}
					$run_color = $modules[ $y ][ $x ];
					$run       = 1;
				}
			}

			if ( $run >= 5 ) {
				$penalty += 3 + ( $run - 5 );
			}
		}

		for ( $y = 0; $y < $size - 1; $y++ ) {
			for ( $x = 0; $x < $size - 1; $x++ ) {
				$color = $modules[ $y ][ $x ];

				if ( $color === $modules[ $y ][ $x + 1 ] && $color === $modules[ $y + 1 ][ $x ] && $color === $modules[ $y + 1 ][ $x + 1 ] ) {
					$penalty += 3;
				}
			}
		}

		$penalty += self::get_finder_like_penalty( $modules, true );
		$penalty += self::get_finder_like_penalty( $modules, false );

		$dark = 0;

		for ( $y = 0; $y < $size; $y++ ) {
			for ( $x = 0; $x < $size; $x++ ) {
				if ( $modules[ $y ][ $x ] ) {
					$dark++;
				}
			}
		}

		$percent = ( $dark * 100 ) / ( $size * $size );
		$penalty += (int) floor( abs( $percent - 50 ) / 5 ) * 10;

		return $penalty;
	}

	/**
	 * Scores finder-like false patterns.
	 *
	 * @param array $modules Matrix.
	 * @param bool  $horizontal Direction.
	 * @return int
	 */
	private static function get_finder_like_penalty( array $modules, $horizontal ) {
		$size     = count( $modules );
		$penalty  = 0;
		$patterns = array(
			array( true, false, true, true, true, false, true, false, false, false, false ),
			array( false, false, false, false, true, false, true, true, true, false, true ),
		);

		for ( $i = 0; $i < $size; $i++ ) {
			for ( $j = 0; $j <= $size - 11; $j++ ) {
				foreach ( $patterns as $pattern ) {
					$matches = true;

					for ( $k = 0; $k < 11; $k++ ) {
						$value = $horizontal ? $modules[ $i ][ $j + $k ] : $modules[ $j + $k ][ $i ];

						if ( $value !== $pattern[ $k ] ) {
							$matches = false;
							break;
						}
					}

					if ( $matches ) {
						$penalty += 40;
					}
				}
			}
		}

		return $penalty;
	}

	/**
	 * Prevent instantiation.
	 */
	private function __construct() {}
}
